"""Generate src/themes.ts from base16 scheme YAML files.

Stdlib only. No PyYAML. We parse just the baseXX hex color lines,
which keeps us independent of full YAML syntax and schema variants.

Usage: python3 tools/gen_themes.py [input_dir]
Default input dir: tools/schemes/base16
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_DIR = ROOT / 'tools' / 'schemes' / 'base16'
OUT = ROOT / 'src' / 'themes.ts'

# Custom TerraForge dark scheme. Tiffany-blue accent on base0D.
TERRAFORGE = {
    'base00': '#191714', 'base01': '#221f1b', 'base02': '#2c2925', 'base03': '#4a463f',
    'base04': '#8a857c', 'base05': '#d6d2c8', 'base06': '#e8e5dd', 'base07': '#f5f2ea',
    'base08': '#d14d41', 'base09': '#da702c', 'base0A': '#d0a215', 'base0B': '#879a39',
    'base0C': '#3aa99f', 'base0D': '#81d8d0', 'base0E': '#7f5caf', 'base0F': '#d47cd6',
}

DEFAULT_THEME = 'flexoki-light'
# Only hex color assignments like:  base0D: "#81d8d0"
COLOR_RE = re.compile(r'^\s*(base[0-9A-F]{2}):\s*["\']?(#[0-9A-Fa-f]{6})')
KEYS = [f'base{i:02x}' for i in range(16)] + [f'base{i:x}' for i in range(10, 16)]
KEYS = [f'base{i:02X}' for i in range(16)]


def parse(path: pathlib.Path) -> dict[str, str] | None:
    scheme: dict[str, str] = {}
    for line in path.read_text(encoding='utf-8', errors='replace').splitlines():
        m = COLOR_RE.match(line)
        if m:
            scheme[m.group(1)] = m.group(2).lower()
    if len(scheme) != 16:
        return None
    return scheme


def main() -> None:
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DIR
    if not src.is_dir():
        sys.exit(f'scheme dir not found: {src}')
    themes: dict[str, dict[str, str]] = {}
    for path in sorted(src.glob('*.yaml')):
        scheme = parse(path)
        if scheme:
            themes[path.stem] = scheme
    if DEFAULT_THEME not in themes:
        sys.exit(f'missing required scheme: {DEFAULT_THEME}')

    lines = [
        '// generated by tools/gen_themes.py - do not edit; regenerate with python3 tools/gen_themes.py',
        '',
        'export interface Base16Scheme {',
    ]
    for k in KEYS:
        lines.append(f'  {k}: string;')
    lines += [
        '}',
        '',
        '// TerraForge custom dark scheme. Tiffany-blue accent.',
        'export const THEMES: Record<string, Base16Scheme> = {',
        "  'terraforge-tiffany': {",
    ]
    for k in KEYS:
        lines.append(f"  {k}: '{TERRAFORGE[k]}',")
    lines += [
        '  },',
    ]
    for name in sorted(themes):
        fields = ', '.join(f"{k}: '{themes[name][k]}'" for k in KEYS)
        lines.append(f"  '{name}': {{ {fields} }},")
    lines += [
        '};',
        '',
        "export const DEFAULT_THEME = 'flexoki-light';",
        '',
    ]
    OUT.write_text('\n'.join(lines))
    print(f'themes: {len(themes) + 1} schemes -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
